apiVersion: v1
kind: Template
metadata:
  annotations:
    description: ${SERVICE_NAME} router config template
  name: ${SERVICE_NAME}-router-config-template
parameters:
- description: Name of the service
  displayName: Service Name
  name: SERVICE_NAME
objects:
- apiVersion: v1
  kind: Route
  metadata:
    name: ${SERVICE_NAME}
  spec:
    host: ${SERVICE_NAME}
    to:
      kind: Service
      name: ${SERVICE_NAME}
    port:
      targetPort: ${SERVICE_NAME}-http
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None
  status: {}
- apiVersion: v1
  kind: Route
  metadata:
    name: jenkins
  spec:
    host: jenkins
    port:
      targetPort: web
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: jenkins
      weight: 100
    wildcardPolicy: None