apiVersion: v1
kind: Template
metadata:
  annotations:
    description: ${SERVICE_NAME} service config template
  name: ${SERVICE_NAME}-service-config-template
parameters:
- description: Name of the service
  displayName: Service Name
  name: SERVICE_NAME
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: ${SERVICE_NAME}
  spec:
    ports:
    - name: ${SERVICE_NAME}-http
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      deploymentconfig: ${SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}